apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations: {}
  labels:
    app: reviews
    app.kubernetes.io/component: reviews
    app.kubernetes.io/instance: reviews
  name: reviews
spec:
  lookupPolicy:
    local: false
